[project]
name = "plotly-lvlos"
description = "Animated comparison of linear vs logarithmic x-scale effects"
output_dir = "build"

[data.core]
x_file = "data/gdppercapita_ppp_inflation_adjusted.csv"
y_file = "data/life_expectancy_years.csv"
entity_column = "country"
year_column = "year"

[analysis]
min_points_per_year = 5

[enrichment.population]
file = "data/population_total.csv"
column = "population"

[enrichment.gini]
file = "data/Gini_coefficient.csv"
column = "gini"

[visualization]
width = 1200
height = 800

[visualization.animation]
frame_duration_ms = 300
transition_duration_ms = 0
