[project]
name = "plotly-lvlos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.12.0",
    "duckdb>=1.4.3",
    "flake8>=7.3.0",
    "plotly>=6.5.0",
    "pytest>=9.0.2",
]
